server:
  port: 6381
spring:
  application:
    name: camellia-redis-proxy-server

camellia-redis-proxy:
  #  port: 6380 #priority greater than server.port, if missing, use server.port; if setting -6379, proxy will choose a random port
  #  application-name: camellia-redis-proxy-server  #priority greater than spring.application.name, if missing, use spring.application.name
  console-port: 16378 #console port, default 16379, if setting -16379, proxy will choose a random port, if setting 0, will disable console
  password: pass123   #password of proxy, priority less than custom client-auth-provider-class-name
  monitor-enable: false  #monitor enable/disable configure
  monitor-interval-seconds: 60 #monitor data refresh interval seconds
  cluster-mode-enable: true
  cluster-mode-provider-class-name: com.netease.nim.camellia.redis.proxy.cluster.provider.ConsensusProxyClusterModeProvider
  config:
    "cluster.mode.consensus.leader.selector.class.name": "com.netease.nim.camellia.redis.proxy.cluster.provider.RedisConsensusLeaderSelector"
    "proxy.cluster.mode.command.move.always": true
    "redis.consensus.leader.selector.redis.key": "c667ae51-e558-e1b6-e96b-ffb21fafbc0a"
    "redis.consensus.leader.selector.redis.url": "redis://@127.0.0.1:6379"
  plugins: #plugin list
    - monitorPlugin
    - bigKeyPlugin
    - hotKeyPlugin
  transpond:
    type: local #local、remote、custom
    local:
      type: simple #simple、complex
      resource: redis-kv://d
#      resource: redis://@127.0.0.1:6379
